### ISSUE TITLE
can‘t find decoder.js on vue3.0

### ISSUE THREAD

**Issue by jiaojiren** [bosscheng/jessibuca-vue-ts-demo#1]
![image](https://user-images.githubusercontent.com/48167118/171593572-463ed887-a775-434d-a711-45d64dc6888d.png)
![image](https://user-images.githubusercontent.com/48167118/171593805-13b13d43-a2e9-46f8-be4a-62e7bf00fca9.png)
![image](https://user-images.githubusercontent.com/48167118/171593662-a2034ec3-3582-4b41-9bdd-f6b904def37c.png)

**Comment by bosscheng** [comment]
看下这个配置，http://jessibuca.monibuca.com/api.html#decoder

**Comment by jiaojiren** [comment]
但是我确实是放在同一个目录下了

**Comment by jiaojiren** [comment]
好了找到问题了，Thanks♪(･ω･)ﾉ
